import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  tabScrollContent: { gap: 10, paddingBottom: 100 },

  headerRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  sectionLabel: { fontSize: 22, fontFamily: 'Inter-Bold', color: '#0F172A' },
  addBtn: { borderRadius: 12, overflow: 'hidden' },
  addBtnGradient: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 12, paddingVertical: 8 },
  addBtnText: { fontSize: 13, fontFamily: 'Inter-SemiBold', color: '#FFFFFF' },
  cancelText:{color: '#161515ff'},
  emptyBox: { padding: 40, alignItems: 'center', justifyContent: 'center', borderRadius: 24, gap: 12 },
  emptyText: { fontSize: 14, fontFamily: 'Inter-Medium', color: '#94A3B8' },
  boqGroup: { marginBottom: 12 },
  groupHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end', marginBottom: 6 },
  categoryTitle: { fontSize: 16, fontFamily: 'Inter-Bold', color: '#0F172A' },
  groupTotal: { fontSize: 14, fontFamily: 'Inter-SemiBold', color: '#3B82F6' },
  boqCard: { borderRadius: 24, padding: 4, borderWidth: 1, borderColor: 'rgba(255,255,255,0.4)', backgroundColor: 'rgba(255, 255, 255, 0.6)' },
  boqRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 14 },
  borderBottom: { borderBottomWidth: 1, borderBottomColor: 'rgba(0,0,0,0.05)' },
  boqMain: { flex: 1, paddingRight: 12 },
  rightCol: { alignItems: 'flex-end', justifyContent: 'center', marginLeft: 12, gap: 4 },
  rowActions: { flexDirection: 'row', gap: 8, marginTop: 4 },
  actionIconBtn: { width: 28, height: 28, backgroundColor: '#F8FAFF', borderRadius: 8, justifyContent: 'center', alignItems: 'center', borderWidth: 1, borderColor: '#E2E8F0' },
  nameRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  itemNum: { fontSize: 11, fontFamily: 'Inter-SemiBold', color: '#3B82F6', backgroundColor: '#EFF6FF', paddingHorizontal: 6, paddingVertical: 2, borderRadius: 4 },
  boqName: { fontSize: 14, fontFamily: 'Inter-SemiBold', color: '#1E293B', flex: 1 },
  boqQty: { fontSize: 12, fontFamily: 'Inter-SemiBold', color: '#94A3B8', marginTop: 4 },
  boqPrice: { fontSize: 14, fontFamily: 'Inter-Bold', color: '#0F172A' },
  grandTotalBox: { backgroundColor: '#0F172A', borderRadius: 20, padding: 20, alignItems: 'center', marginTop: 10 },
  grandTotalLabel: { fontSize: 11, fontFamily: 'Inter-SemiBold', color: 'rgba(255,255,255,0.5)', letterSpacing: 1 },
  grandTotalValue: { fontSize: 24, fontFamily: 'Inter-Bold', color: '#FFFFFF', marginTop: 4 },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'center', alignItems: 'center', padding: 24 },
  choiceCard: { width: '100%', borderRadius: 36, padding: 28, gap: 12 },
  modalHeader: { marginBottom: 12 },
  modalTitle: { fontSize: 22, fontFamily: 'Inter-Bold', color: '#0F172A' },
  modalSubtitle: { fontSize: 14, fontFamily: 'Inter-Medium', color: '#64748B', marginTop: 2 },
  choiceBtn: { flexDirection: 'row', alignItems: 'center', gap: 14, padding: 16, backgroundColor: '#FFFFFF', borderRadius: 24, borderWidth: 1, borderColor: '#E2E8F0' },
  choiceIconBox: { width: 48, height: 48, borderRadius: 16, justifyContent: 'center', alignItems: 'center' },
  choiceTextCol: { flex: 1 },
  choiceBtnTitle: { fontSize: 16, fontFamily: 'Inter-SemiBold', color: '#1E293B' },
  choiceBtnSub: { fontSize: 12, fontFamily: 'Inter-Medium', color: '#64748B', marginTop: 2 },
  cancelLink: { marginTop: 8, paddingVertical: 12, alignItems: 'center' },
  cancelLinkText: { fontSize: 14, fontFamily: 'Inter-SemiBold', color: '#94A3B8' },
  formCard: { width: '100%', maxHeight: '80%', borderRadius: 32, padding: 24 },
  inputLabel: { fontSize: 13, fontFamily: 'Inter-SemiBold', color: '#64748B', marginBottom: 8, marginTop: 16 },
  input: { backgroundColor: '#FFFFFF', borderRadius: 16, padding: 16, fontSize: 15, fontFamily: 'Inter-SemiBold', color: '#0F172A', borderWidth: 1, borderColor: '#E2E8F0' },
  inputRow: { flexDirection: 'row' },
  groupChip: { backgroundColor: '#F1F5F9', paddingHorizontal: 12, paddingVertical: 8, borderRadius: 12, marginRight: 8, borderWidth: 1, borderColor: '#E2E8F0' },
  groupChipActive: { backgroundColor: '#EFF6FF', borderColor: '#3B82F6' },
  groupChipText: { fontSize: 13, fontFamily: 'Inter-Medium', color: '#64748B' },
  groupChipTextActive: { color: '#3B82F6', fontFamily: 'Inter-SemiBold' },
  autocompleteDropdown: { backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E2E8F0', borderRadius: 16, marginTop: 8, overflow: 'hidden', elevation: 2, shadowColor: '#000', shadowOpacity: 0.05, shadowRadius: 8, shadowOffset: { width: 0, height: 4 } },
  autocompleteItem: { paddingVertical: 14, paddingHorizontal: 16, borderBottomWidth: 1, borderBottomColor: '#F1F5F9' },
  autocompleteItemText: { fontSize: 14, fontFamily: 'Inter-Medium', color: '#1E293B' },
  modalActions: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, marginTop: 12, marginBottom: 4, paddingTop: 16, borderTopWidth: 1, borderTopColor: 'rgba(0,0,0,0.05)' },
  formCancelBtn: { flex: 1, minWidth: 100, height: 56, justifyContent: 'center', alignItems: 'center', borderRadius: 18, borderWidth: 1, borderColor: '#EF4444' },
  submitBtn: { flex: 2, minWidth: 150, borderRadius: 18, overflow: 'hidden' },
  submitGradient: { height: 56, justifyContent: 'center', alignItems: 'center' },
  submitText: { fontSize: 15, fontFamily: 'Inter-Bold', color: '#FFFFFF' },
  previewCard: {
    width: '100%',
    maxHeight: '85%',
    borderRadius: 32,
    padding: 24,
    backgroundColor: '#FFFFFF',
  },
  previewList: {
    marginVertical: 20,
    maxHeight: 400,
  },
  previewRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  previewGroupName: {
    fontSize: 10,
    fontFamily: 'Inter-SemiBold',
    color: '#3B82F6',
    textTransform: 'uppercase',
    marginBottom: 2,
  },
  previewDesc: {
    fontSize: 14,
    fontFamily: 'Inter-SemiBold',
    color: '#1E293B',
  },
  previewTotal: {
    fontSize: 15,
    fontFamily: 'Inter-Bold',
    color: '#0F172A',
  },
  previewDetails: {
    fontSize: 11,
    fontFamily: 'Inter-Medium',
    color: '#64748B',
  },
  versionBadge: {
    backgroundColor: '#F1F5F9',
    paddingHorizontal: 6,
    paddingVertical: 1,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  versionText: {
    fontSize: 9,
    fontFamily: 'Inter-SemiBold',
    color: '#64748B',
  },
  historyCard: { width: '100%', maxHeight: '80%', borderRadius: 32, padding: 24, backgroundColor: '#FFFFFF' },
  historyList: { marginVertical: 16 },
  historyItem: { flexDirection: 'row', marginBottom: 0 },
  historyDotCol: { alignItems: 'center', width: 24, marginRight: 12 },
  historyDot: { width: 12, height: 12, borderRadius: 6, backgroundColor: '#E2E8F0', marginTop: 6, zIndex: 1 },
  latestDot: { backgroundColor: '#3B82F6', transform: [{ scale: 1.2 }] },
  historyLine: { width: 2, flex: 1, backgroundColor: '#F1F5F9', marginVertical: -4 },
  historyContent: { flex: 1, paddingBottom: 24 },
  historyHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 },
  historyVersion: { fontSize: 14, fontFamily: 'Inter-Bold', color: '#0F172A' },
  historyUser: { fontSize: 11, fontFamily: 'Inter-SemiBold', color: '#3B82F6' },
  historyDate: { fontSize: 10, fontFamily: 'Inter-Medium', color: '#94A3B8' },
  historyDataRow: { flexDirection: 'row', alignItems: 'flex-end' },
  historyLabel: { fontSize: 10, fontFamily: 'Inter-SemiBold', color: '#94A3B8', textTransform: 'uppercase', marginBottom: 2 },
  historyValue: { fontSize: 14, fontFamily: 'Inter-SemiBold', color: '#1E293B' },
  historyTotal: { fontSize: 16, fontFamily: 'Inter-Bold', color: '#0F172A' },
  historyRemark: { fontSize: 12, fontFamily: 'Inter-Medium', color: '#64748B', fontStyle: 'italic', marginTop: 8, backgroundColor: '#F8FAFC', padding: 8, borderRadius: 8 },
  historyCloseBtn: { height: 50, backgroundColor: '#F1F5F9', borderRadius: 16, justifyContent: 'center', alignItems: 'center', marginTop: 8 },
  historyCloseText: { fontSize: 14, fontFamily: 'Inter-SemiBold', color: '#475569' },
  viewCard: { width: '100%', maxHeight: '85%', borderRadius: 32, padding: 24, backgroundColor: '#FFFFFF', position: 'relative' },
  viewCloseBtn: { position: 'absolute', top: 14, right: 14, zIndex: 10, width: 32, height: 32, borderRadius: 16, backgroundColor: '#F1F5F9', alignItems: 'center', justifyContent: 'center' },
  detailBody: { marginVertical: 16 },
  detailRow: { marginBottom: 16 },
  detailLabel: { fontSize: 11, fontFamily: 'Inter-SemiBold', color: '#94A3B8', textTransform: 'uppercase', marginBottom: 4 },
  detailValue: { fontSize: 16, fontFamily: 'Inter-SemiBold', color: '#0F172A' },
  detailDesc: { fontSize: 15, fontFamily: 'Inter-Medium', color: '#334155', lineHeight: 22 },
  statsGrid: { flexDirection: 'row', gap: 12, marginBottom: 16 },
  statBox: { flex: 1, backgroundColor: '#F8FAFC', padding: 12, borderRadius: 16, borderWidth: 1, borderColor: '#F1F5F9' },
  statLabel: { fontSize: 10, fontFamily: 'Inter-SemiBold', color: '#64748B', textTransform: 'uppercase', marginBottom: 4 },
  statValue: { fontSize: 16, fontFamily: 'Inter-Bold', color: '#0F172A' },
  totalBox: { backgroundColor: '#F0F9FF', padding: 16, borderRadius: 20, marginBottom: 16, borderLeftWidth: 4, borderLeftColor: '#3B82F6' },
  totalLabel: { fontSize: 11, fontFamily: 'Inter-SemiBold', color: '#3B82F6', textTransform: 'uppercase', marginBottom: 4 },
  totalValue: { fontSize: 24, fontFamily: 'Inter-Bold', color: '#0F172A' },
  remarkBox: { backgroundColor: '#F1F5F9', padding: 12, borderRadius: 16, marginBottom: 16 },
  remarkText: { fontSize: 13, fontFamily: 'Inter-Medium', color: '#475569', lineHeight: 20 },
  auditBox: { paddingTop: 16, borderTopWidth: 1, borderTopColor: '#F1F5F9', alignItems: 'center' },
  auditLabel: { fontSize: 11, fontFamily: 'Inter-SemiBold', color: '#94A3B8' },
  auditDate: { fontSize: 10, fontFamily: 'Inter-Medium', color: '#CBD5E1', marginTop: 2 },
  viewActions: { flexDirection: 'row', gap: 12, marginTop: 12 },
  historyBtn: { flex: 1, height: 50, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, borderRadius: 16, backgroundColor: '#EFF6FF', borderWidth: 1, borderColor: '#DBEAFE' },
  historyBtnText: { fontSize: 14, fontFamily: 'Inter-SemiBold', color: '#3B82F6' },
  editBtn: { flex: 1, borderRadius: 16, overflow: 'hidden' },
  editGradient: { height: 50, flexDirection: 'row', justifyContent: 'center', alignItems: 'center' },
  editText: { fontSize: 14, fontFamily: 'Inter-Bold', color: '#FFFFFF' },
  versionTabRow: { marginBottom: 16, paddingBottom: 12, borderBottomWidth: 1, borderBottomColor: '#F1F5F9' },
  versionTab: { paddingHorizontal: 16, paddingVertical: 8, borderRadius: 12, backgroundColor: '#F8FAFC', marginRight: 8, borderWidth: 1, borderColor: '#E2E8F0' },
  activeTab: { backgroundColor: '#3B82F6', borderColor: '#3B82F6' },
  versionTabText: { fontSize: 12, fontFamily: 'Inter-SemiBold', color: '#64748B' },
  activeTabText: { color: '#FFFFFF' },
  readOnlyNote: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, padding: 12, backgroundColor: '#F8FAFC', borderRadius: 16, borderStyle: 'dashed', borderWidth: 1, borderColor: '#E2E8F0' },
  readOnlyText: { fontSize: 13, fontFamily: 'Inter-Medium', color: '#64748B' },
  qtyStatusRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 4 },
  statusBadge: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 8, paddingVertical: 2, borderRadius: 6, gap: 4 },
  statusDot: { width: 4, height: 4, borderRadius: 2, backgroundColor: '#FFF' },
  statusPending: { backgroundColor: 'rgba(245, 158, 11, 0.15)', borderWidth: 1, borderColor: 'rgba(245, 158, 11, 0.3)' },
  statusDraft: { backgroundColor: 'rgba(100, 116, 139, 0.15)', borderWidth: 1, borderColor: 'rgba(100, 116, 139, 0.3)' },
  statusApproved: { backgroundColor: 'rgba(16, 185, 129, 0.15)', borderWidth: 1, borderColor: 'rgba(16, 185, 129, 0.3)' },
  statusRejected: { backgroundColor: 'rgba(239, 68, 68, 0.15)', borderWidth: 1, borderColor: 'rgba(239, 68, 68, 0.3)' },
  statusText: { fontSize: 9, fontFamily: 'Inter-SemiBold' },
  statusPending_text: { color: '#D97706' },
  statusApproved_text: { color: '#059669' },
  statusRejected_text: { color: '#DC2626' },
  viewStatusBox: { marginTop: 16, paddingTop: 16, borderTopWidth: 1, borderTopColor: '#F1F5F9' },
  decisionAudit: { marginTop: 12, paddingLeft: 12, borderLeftWidth: 2, borderLeftColor: '#E2E8F0' },
  viewStatusBadge: { flexDirection: 'row', alignItems: 'center', gap: 8, alignSelf: 'flex-start', paddingHorizontal: 14, paddingVertical: 8, borderRadius: 12 },
  statusPending_solid: { backgroundColor: '#F59E0B' },
  statusDraft_solid: { backgroundColor: '#64748B' },
  statusApproved_solid: { backgroundColor: '#10B981' },
  statusRejected_solid: { backgroundColor: '#F43F5E' },
  viewStatusText: { fontSize: 13, fontFamily: 'Inter-Bold', color: '#FFFFFF', textTransform: 'uppercase' },
  approvalWrapper: { width: '100%', backgroundColor: '#F8FAFC', padding: 20, borderRadius: 28, borderTopWidth: 1, borderTopColor: '#F1F5F9', marginTop: 8 },
  approvalTitle: { fontSize: 11, fontFamily: 'Inter-Bold', color: '#94A3B8', textTransform: 'uppercase', marginBottom: 16, textAlign: 'center', letterSpacing: 1 },
  approvalActions: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, width: '100%' },
  approvalBtn: { flex: 1, minWidth: 120, height: 52, borderRadius: 18, justifyContent: 'center', alignItems: 'center' },
  approveBtnSolid: { backgroundColor: '#10B981' },
  rejectBtnSolid: { backgroundColor: '#F43F5E' },
  approvalBtnTextSolid: { fontSize: 14, fontFamily: 'Inter-Bold', color: '#FFFFFF' },
  selectionHeader: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  selectionLeft: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  selectAllBtn: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: '#EFF6FF', paddingHorizontal: 10, paddingVertical: 6, borderRadius: 10, borderWidth: 1, borderColor: '#DBEAFE' },
  selectAllText: { fontSize: 13, fontFamily: 'Inter-SemiBold', color: '#3B82F6' },
  selectionCount: { fontSize: 15, fontFamily: 'Inter-Bold', color: '#0F172A' },
  selectionActions: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  selectionActionBtn: { height: 40, flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 12, borderRadius: 12, justifyContent: 'center' },
  bulkApproveBtn: { backgroundColor: '#10B981' },
  bulkDeleteBtn: { backgroundColor: '#EF4444', width: 40, paddingHorizontal: 0 },
  bulkActionText: { fontSize: 13, fontFamily: 'Inter-Bold', color: '#FFFFFF' },
  selectionIconBtn: { width: 40, height: 40, borderRadius: 12, backgroundColor: '#FFFFFF', justifyContent: 'center', alignItems: 'center', borderWidth: 1, borderColor: '#E2E8F0' },
  selectionBox: { paddingRight: 12, justifyContent: 'center' },
  selectedCard: { borderColor: '#3B82F6', backgroundColor: '#F0F9FF', borderWidth: 2 },
  boqItemsContainer: { gap: 12 },
  boqModernCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.85)',
    borderRadius: 28,
    paddingHorizontal: 18,
    paddingVertical: 16,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    position: 'relative',
    overflow: 'hidden'
  },
  pendingCardModern: {
    borderColor: 'rgba(245, 158, 11, 0.4)',
    backgroundColor: '#FFFCF5',
  },
  pendingPulseContainer: { position: 'absolute', top: 12, right: 12, width: 20, height: 20, justifyContent: 'center', alignItems: 'center' },
  pendingPulse: { position: 'absolute', width: 24, height: 24, borderRadius: 12, backgroundColor: '#F59E0B', opacity: 0.15 },
  pendingPulseCore: { width: 8, height: 8, borderRadius: 4, backgroundColor: '#F59E0B', borderWidth: 2, borderColor: '#FFFFFF' },
  groupAccent: { width: 4, height: 16, backgroundColor: '#3B82F6', borderRadius: 10 },
  groupHeaderLeft: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  qtyDot: { width: 3, height: 3, borderRadius: 1.5, backgroundColor: '#CBD5E1', marginHorizontal: 3 },
  approverList: { marginVertical: 16, maxHeight: 380 },
  approverItemModern: { 
    flexDirection: 'row', 
    alignItems: 'center', 
    padding: 14, 
    backgroundColor: '#F8FAFC', 
    borderRadius: 24, 
    marginBottom: 10, 
    borderWidth: 1, 
    borderColor: 'transparent' 
  },
  selectedApproverModern: { 
    backgroundColor: '#FFFFFF', 
    borderColor: '#3B82F6', 
    shadowColor: '#3B82F6',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 4
  },
  avatarBox: { 
    width: 48, 
    height: 48, 
    borderRadius: 18, 
    backgroundColor: '#E2E8F0', 
    justifyContent: 'center', 
    alignItems: 'center',
    marginRight: 14
  },
  avatarBoxActive: { backgroundColor: '#EFF6FF' },
  avatarText: { fontSize: 16, fontFamily: 'Inter-Bold', color: '#64748B' },
  avatarTextActive: { color: '#3B82F6' },
  approverInfoModern: { flex: 1 },
  nameRowModern: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  approverNameModern: { fontSize: 15, fontFamily: 'Inter-Bold', color: '#0F172A', flex: 1 },
  approverRoleModern: { fontSize: 12, fontFamily: 'Inter-SemiBold', color: '#3B82F6', marginTop: 1 },
  approverEmailModern: { fontSize: 11, fontFamily: 'Inter-Medium', color: '#94A3B8', marginTop: 2 },
  tagBadge: { backgroundColor: '#F0FDF4', paddingHorizontal: 6, paddingVertical: 2, borderRadius: 6 },
  tagBadgeText: { fontSize: 8, fontFamily: 'Inter-Bold', color: '#16A34A', textTransform: 'uppercase' },
  radioOuter: { 
    width: 22, 
    height: 22, 
    borderRadius: 11, 
    borderWidth: 2, 
    borderColor: '#CBD5E1', 
    justifyContent: 'center', 
    alignItems: 'center',
    marginLeft: 10
  },
  radioOuterActive: { borderColor: '#3B82F6' },
  radioInner: { width: 10, height: 10, borderRadius: 5, backgroundColor: '#3B82F6' },
  emptyApproverBox: { padding: 32, alignItems: 'center', gap: 8 },
  emptyApproverText: { fontSize: 14, fontFamily: 'Inter-Medium', color: '#94A3B8' },
  approverCard: { width: '100%', borderRadius: 36, padding: 24, backgroundColor: '#FFFFFF' },
  impactCard: { width: '100%', borderRadius: 36, padding: 24, backgroundColor: '#FFFFFF' },
  impactHeader: { flexDirection: 'row', alignItems: 'center', gap: 16, marginBottom: 20 },
  impactIconBox: { width: 48, height: 48, borderRadius: 16, backgroundColor: '#EFF6FF', justifyContent: 'center', alignItems: 'center' },
  impactTitle: { fontSize: 20, fontFamily: 'Inter-Bold', color: '#0F172A' },
  impactSubtitle: { fontSize: 13, fontFamily: 'Inter-Medium', color: '#64748B' },
  comparisonGrid: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 20 },
  compareBox: { flex: 1, gap: 4 },
  compareLabel: { fontSize: 11, fontFamily: 'Inter-SemiBold', color: '#94A3B8', textTransform: 'uppercase' },
  compareAmount: { fontSize: 18, fontFamily: 'Inter-Bold', color: '#64748B' },
  diffBox: { padding: 20, borderRadius: 24, alignItems: 'center', marginBottom: 20 },
  diffLabel: { fontSize: 11, fontFamily: 'Inter-Bold', letterSpacing: 1 },
  diffValue: { fontSize: 28, fontFamily: 'Inter-Bold', marginTop: 4 },
  autoReasonBox: { padding: 16, backgroundColor: '#F8FAFC', borderRadius: 16, marginBottom: 20, borderLeftWidth: 3, borderLeftColor: '#3B82F6' },
  autoReasonLabel: { fontSize: 10, fontFamily: 'Inter-Bold', color: '#94A3B8', marginBottom: 4 },
  autoReasonText: { fontSize: 13, fontFamily: 'Inter-Medium', color: '#334155', fontStyle: 'italic' },
});
